Use the new Affiliation xpath in EntrezScraper
rayyansys/rayyan-scrapers pull request #14
Opened 2022-07-08 03:50 UTC by kohrVid

GH Issue: https://github.com/rayyansys/rayyan-scrapers/issues/1

Following a change in the the Entrez API, affiliations must now be taken from the Author object. This PR attempts to maintain backwards compatibility by only checking the new affiliation xpath if the article affiliation is nil. However, this also means that the scraper will only return the first affiliation if there is more than one

### Questions

* Should we directly associate the affiliation with the `authors` attribute in the `RayyanFormats::Target` model? At the moment ,`RayyanFormats::Target#authors` returns an array of strings containing the authors' names. I think the change to the Entrez API suggests that an article could have more than one affiliation. If that's the case, should we update our data model to take this into account?

2022-07-19 20:30 UTC, hammady commented on lib/rayyan-scrapers/entrez_scraper.rb
> +      mArticle.affiliation ||= extract_xpath_text xml, './AuthorList/Author/AffiliationInfo/Affiliation'
@kohrVid

2022-07-20 02:41 UTC, kohrVid commented on lib/rayyan-scrapers/entrez_scraper.rb
> +      mArticle.affiliation ||= extract_xpath_text xml, './AuthorList/Author/AffiliationInfo/Affiliation'
I've pushed a change to this PR that I think would address this issue but it breaks one of the [pubmed tests](https://github.com/rayyansys/rayyan-scrapers/blob/master/spec/rayyan-formats-pubmed_xml_spec.rb#L24) for some reason. The spec kind of looks like its testing the `import` method from the core gem which doesn't seem necessary in this repo. Is it all right if I remove the test? If not, do you remember why it was added?

2022-07-20 23:11 UTC, hammady commented on lib/rayyan-scrapers/entrez_scraper.rb
> +        ((xml/"./AuthorList/Author")[0]/"AffiliationInfo/Affiliation").text
Does this cover the case where the xpath `./AuthorList/Author` returns just one element? Can we add a test for that?

2022-07-20 23:15 UTC, hammady commented on lib/rayyan-scrapers/entrez_scraper.rb
> +      mArticle.affiliation ||= extract_xpath_text xml, './AuthorList/Author/AffiliationInfo/Affiliation'
It doesn't really test the base import per se. In the same file, the `before` hook [registers](https://github.com/rayyansys/rayyan-scrapers/blame/master/spec/rayyan-formats-pubmed_xml_spec.rb#L18) the plugin that is offered by this repo. That spec then tests that parsing is successful and that it yields those args.

2022-07-21 15:50 UTC, kohrVid commented on lib/rayyan-scrapers/entrez_scraper.rb
> +      mArticle.affiliation ||= extract_xpath_text xml, './AuthorList/Author/AffiliationInfo/Affiliation'
Ok...I'm still not sure if it's strictly a "unit" test in that case but I suppose this _is_ a gem so it's probably fine. I've tried stubbing out the `#extract_affiliation` method in that file as I can't figure out another way to get both of those specs to pass. When I compare the output when I search for the title of [this article](https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&retmode=xml&id=17577129) with this branch to when I'm on the master branch, the affiliation looks like it's been extracted correctly. I've also added another test for when there's only one author present. Is that ok?

2022-07-21 15:54 UTC, hammady requested changes

2022-07-21 15:54 UTC, hammady commented on spec/rayyan-formats-pubmed_xml_spec.rb
> +    allow_any_instance_of(RayyanScrapers::EntrezScraper).to receive(:extract_affiliation).and_return(nil)
I checked the failing test and I don't think it is correct to ignore it. We need to fix the failing test, otherwise we might have just introduced a regression bug causing imports to return unexpected results.

2022-07-21 15:57 UTC, hammady commented on lib/rayyan-scrapers/entrez_scraper.rb
> +      mArticle.affiliation ||= extract_xpath_text xml, './AuthorList/Author/AffiliationInfo/Affiliation'
I don't think it is natural to stub affiliation extraction in this test, why not stubbing authors, titles, dois? There must be something wrong introduced by affiliation.

2022-07-21 20:38 UTC, kohrVid commented on lib/rayyan-scrapers/entrez_scraper.rb
> +      mArticle.affiliation ||= extract_xpath_text xml, './AuthorList/Author/AffiliationInfo/Affiliation'
So far, all I can see is that the use of the index (`[0]`) causes the test to fail. Adding something like...

    mArticle.affiliation ||= ((xml/"./AuthorList/Author")[0]/"AffiliationInfo/Affiliation").text
    
..or...

    mArticle.affiliation ||= (xml/'./AuthorList/Author/AffiliationInfo/Affiliation').first.text

...will return the correct institution but will break the PubmedXML test. Adding something like...

    mArticle.affiliation ||= (xml/'./AuthorList/Author/AffiliationInfo/Affiliation').text

...(where `.first` or `[0]` are missing) won't break the test but will return all institutions in a list instead of the first one, causing the affiliation test to fail.

My assumption is that the PubmedXML test depends on something that would normally stub out the Nokogiri helper methods but doesn't know how to handle arrays that are modified in this way. Not really sure how to handle this as far as the PubMed test is concerned

2022-07-21 22:39 UTC, hammady approved these changes

2022-07-21 22:40 UTC, merged