Use GitHub actions
rayyansys/rayyan-scrapers pull request #16
Opened 2022-07-15 22:56 UTC by kohrVid

Closes #13 .

This PR replaces our Travis CI configuration with a Github Action workflow. The workflow has been set up to run rspec tests with the following rubies:

* 2.3 - failing
* 2.4 - failing
* 2.5 - failing
* 2.6 - failing
* 2.7 - failing

An example of the CI job can be found on my fork of this repo [here](https://github.com/kohrVid/rayyan-scrapers/runs/7365151088?check_suite_focus=true).

2022-07-18 20:36 UTC, hammady requested changes

2022-07-18 20:36 UTC, hammady commented on .coveralls.yml
> +service_name: github-actions
Remove if unnecessary.

2022-07-19 17:49 UTC, hammady commented on rayyan-scrapers.gemspec
> +  spec.add_development_dependency 'simplecov', '~> 0.14.1'
Why not 0.16?

2022-07-19 17:51 UTC, kohrVid commented on rayyan-scrapers.gemspec
> +  spec.add_development_dependency 'simplecov', '~> 0.14.1'
I just used the version that was replaced in the core repo. I can try upgrading to 0.16 if you'd prefer

2022-07-19 17:52 UTC, hammady commented on rayyan-scrapers.gemspec
> +  spec.add_development_dependency 'simplecov', '~> 0.14.1'
I noticed that this repo was using 0.16, that's why I was curious to know why we downgraded it.

2022-07-19 17:56 UTC, kohrVid commented on rayyan-scrapers.gemspec
> +  spec.add_development_dependency 'simplecov', '~> 0.14.1'
No worries - I just copied and pasted from the earlier PR. I think v0.17.1 still supports ruby 2.3 so we _could_ use that

2022-07-19 18:34 UTC, hammady commented
@kohrVid please update the PR descriptions on all repos (ignoring coveralls being down) so that I can merge.

2022-07-19 18:38 UTC, hammady approved these changes

2022-07-19 20:28 UTC, hammady approved these changes

2022-07-19 20:28 UTC, merged