Add MendeleyScraper
rayyansys/rayyan-scrapers pull request #23
Opened 2022-11-30 23:20 UTC by kohrVid

GH Issue: #21

This PR adds new class for the MendeleyScraper. The expected usage  is:

    articles = []
    access_token = "ACCESS_TOKEN"
    collection_ids = [folder_id_1, folder_id_2]
    scraper = RayyanScrapers::MendeleyScraper.new(access_token, "folders", collection_ids)
    scraper.scrape do |article, total|
      articles << { total: total, article: article }
    end

Note, the access token, collection type and collection IDs are passed into the initialise method and not `#scrape` which seems more inline with the setup in previous plugins

2022-12-01 19:45 UTC, hammady requested changes
Also need to update the README with examples for the new class.

2022-12-01 19:45 UTC, hammady commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +  class MendeleyScraper < EntrezScraper
Entrez is the API implemented and hosted by [NCBI](https://www.ncbi.nlm.nih.gov/) and thus not compatible with Mendeley API. I suggest that we subclass the `ScraperBase` directly.

2022-12-01 19:45 UTC, hammady commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +    def initialize(logger = nil, moneta_options = nil, access_token, collection_type, collection_ids)
Parameters with default values should come at the end.

2022-12-01 19:45 UTC, hammady commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +      yield JSON.parse(page.body) if block_given?
Need to map Mendeley schema to the gem schema found in the README.

2022-12-01 19:45 UTC, hammady commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +      raise page["message"] if page.is_a?(Hash) && page["message"].present?
What are possible values for the message? Isn't it safer to check for a 401 status code?

2022-12-01 19:45 UTC, hammady commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +      url = "#{@base_url}/documents/#{id}"
What about checking the token here too?

2022-12-01 21:04 UTC, kohrVid commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +      raise page["message"] if page.is_a?(Hash) && page["message"].present?
Well originally that method was created because the the `#get_start_page` method would parse the API response even when it had returned an error, leading to unexpected results when the access token expired. In that case, the parsed API response was always a hash with a `message` key. I think you have a point though and wonder if it would be better to check the response code before the response is parsed. I'm looking into that right now

2022-12-03 00:05 UTC, kohrVid commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +  class MendeleyScraper < EntrezScraper
Have updated the class so this should be fixed now

2022-12-03 00:06 UTC, kohrVid commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +    def initialize(logger = nil, moneta_options = nil, access_token, collection_type, collection_ids)
Sorry - this should be fixed as well now

2022-12-03 00:10 UTC, kohrVid commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +      yield JSON.parse(page.body) if block_given?
Right, apologies for missing that out earlier. Formatting the response required a lot of refactoring but hopefully should be done now as well. Let me know if you have any feedback about the latest commit

2022-12-03 02:44 UTC, hammady commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +      if page.is_a?(Typhoeus::Response) && page.response_code != 200
This is an improvement over the previous implementation. It can be improved further by doing 2 things:
1. Explicitly checking for the unauthorized status code (401) which clearly denotes there is a problem in the access token
2. Always raising an error with a message explaining the above
3. Additionally if there is a message in the JSON response, append it because currently no raising happens if the response is not a hash although the status code is not 200
4. I suggest expanding the scope of this method by checking for server errors too (other 4xx and 5xx) and thus renaming it. Basically it will check if 200 -> we are good, else -> raise an error with the returned code and append message from JSON response if any

2022-12-03 02:45 UTC, hammady commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +      yield JSON.parse(page.body) if block_given?
This needs more time, I will review the mapping tomorrow/after.

2022-12-04 17:22 UTC, hammady requested changes

2022-12-04 17:22 UTC, hammady commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +        label: nil,
No need for assigning `nil` values.

2022-12-04 17:22 UTC, hammady commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +      mArticle.authors = item['authors'].map do |author|
Check if `authors` is not found.

2022-12-04 17:22 UTC, hammady commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +        mArticle.journal_issn = item['identifiers']['issn']
Check if `identifiers` is not found.

2022-12-04 17:22 UTC, hammady commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +        mArticle.journal_abbreviation = item['short_title']
These are not the same. Remove.

2022-12-04 17:22 UTC, hammady commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +        mArticle.doi = item['identifiers']['doi']
Check if `identifiers` is not found.

2022-12-04 17:22 UTC, hammady commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +      mArticle.article_ids = item['identifiers'].map do |type, id|
Check if `identifiers` is not found.

2022-12-04 17:22 UTC, hammady commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +      return mArticle.date_array = nil unless item['year'].present?
`present?` is Rails specific and is the opposite of `blank?`.

2022-12-04 17:22 UTC, hammady commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +      return mArticle.date_array = nil unless item['year'].present?
This and the above, should have been caught by tests if this case is covered.

2022-12-04 17:22 UTC, hammady commented on spec/mendeley_scraper_spec.rb
> +  describe '#parse_search_results' do
Need to add tests to check for correct assignment of simple fields, e.g. `expect(title).to eq(put_title_value_from_example_file)`

2022-12-04 17:22 UTC, hammady commented
> Also need to update the README with examples for the new class.

@kohrVid Please don't forget this.

2022-12-04 17:24 UTC, hammady commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +      yield JSON.parse(page.body) if block_given?
Reviewed.

2022-12-06 17:33 UTC, kohrVid commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +      if page.is_a?(Typhoeus::Response) && page.response_code != 200
I'm not sure that it makes sense to explicitly check for 401s because what used to happen was that Mendeley API would return a 401 response with a hash that explicitly said that there was a problem with the token and this was what the gem would raise for the user. The `#check_access_token` method didn't log the error however and it also wouldn't return an error if the API response wasn't a hash. I've tried to fix that in the latest commit (and renamed the method as part of that change) though perhaps the format of the error could still do with some work. Let me know what you think

2022-12-06 17:34 UTC, kohrVid commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +      check_access_token(page)
This should be fixed now

2022-12-06 17:35 UTC, kohrVid commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +        mArticle.url = "#{@detail_friendly_url}#{id}?view=all"
Thanks for the pointer. Should be fixed now

2022-12-06 17:36 UTC, kohrVid commented on spec/mendeley_scraper_spec.rb
> +  describe '#parse_search_results' do
Have added specs for all of the fields so hopefully that's ok now

2022-12-06 17:39 UTC, kohrVid commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +      mArticle.article_ids = item['identifiers'].map do |type, id|
Previously there was a test for `identifiers` that were an empty object but I've changed it to test nil identifiers for consistency. Hopefully that's ok

2022-12-06 19:34 UTC, hammady requested changes

2022-12-06 19:34 UTC, hammady commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +        mArticle.url = item['websites'].first
This can be nil.

2022-12-06 19:34 UTC, hammady commented on spec/mendeley_scraper_spec.rb
> +        mendeley_scraper.parse_search_results(page).sid
I usually don't comment on specs syntax, but this one saves a lot of ink:
```ruby
  let(:article) { mendeley_scraper.parse_search_results(page) }
```
Then use it down the line.

2022-12-06 19:34 UTC, hammady commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +        @logger.error error_message
I'd always prefix the error message with the non-200 status code like line 154. You can remove the `else` block in lines 155-156, the prefix in 154 and transform the error message to `#{parsed_page.response_code}: #{parsed_page.to_s}`

2022-12-06 19:34 UTC, hammady commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +      if page.is_a?(Typhoeus::Response) && page.response_code != 200
You are right. Point 1 in my previous comment is obsoleted by point 4. I should have removed it after proof-reading my comment.

2022-12-08 00:20 UTC, kohrVid commented on spec/mendeley_scraper_spec.rb
> +        mendeley_scraper.parse_search_results(page).sid
Cheers. I'm not always sure where the right balance is when it comes to variables in tests but this does save a lot of space

2022-12-08 00:22 UTC, kohrVid commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +        @logger.error error_message
I've updated that method so that the response code is used as a prefix for all of the error messages (including the ones that appear in a hash). I hope that's ok

2022-12-08 00:26 UTC, kohrVid commented
Coveralls.io appears to be down at the moment which is why the CI build currently fails/hangs. The tests will probably need to be re-run when the site is up again

2022-12-08 15:52 UTC, hammady commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +        mArticle.url = item['websites'].first
Not done yet.

2022-12-09 08:25 UTC, kohrVid commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +        mArticle.url = item['websites'].first
Should be fixed now

2022-12-12 13:58 UTC, kohrVid commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +      rescue => exception
I've updated the PR based on your suggestion. I wasn't sure if we'd still want to log anything if these individual fields return an error as most of them are nullable. Is this ok as is or should we still log something  where there are unexpected values?

2022-12-12 18:31 UTC, hammady approved these changes

2022-12-12 18:35 UTC, merged