Je add total pages to mendeley
rayyansys/rayyan-scrapers pull request #33
Opened 2022-12-31 16:18 UTC by kohrVid

Closes # 25

Have begun work on fixing the `total_pages` bug. Unfortunately, the `Mendeley-Count` header doesn't seem to be available for Folders and Group URLs so the actual count only appears when a collection type isn't specified. I am unsure of how to handle this as it may be a limitation in the Mendeley API

2023-02-27 23:07 UTC, hammady requested changes

2023-02-27 23:07 UTC, hammady commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +                page.headers['Mendeley-Count']
Try converting to an integer.

2023-02-27 23:07 UTC, hammady commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +      total
No need to set `total` variable and return it.

2023-02-27 23:07 UTC, hammady commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +                'Unknown'
Delegate to `super` in this case.

2023-02-28 15:33 UTC, kohrVid commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +                page.headers['Mendeley-Count']
No problem, I've updated the PR so that the method returns an integer going forwards

2023-02-28 17:48 UTC, hammady approved these changes

2023-02-28 17:49 UTC, merged