Add MendeleyScraper exceptions
rayyansys/rayyan-scrapers pull request #34
Opened 2023-01-09 23:44 UTC by kohrVid

Closes #31

This PR adds a set of exception classes to improve the error handling in the MendeleyScraper.

2023-01-10 02:07 UTC, hammady requested changes

2023-01-10 02:07 UTC, hammady commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +          @logger.error error_message
Let's also print the response code.

2023-01-11 14:28 UTC, kohrVid commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +          @logger.error error_message
Have updated the scraper so that the response code appears in the logs and the exception

2023-01-11 14:29 UTC, kohrVid commented on lib/rayyan-scrapers/mendeley_scraper.rb
>          error_message = if parsed_page.is_a?(Hash)
Have re-added a guard for the response code so this code shouldn't be run when the API returns a 200 anymore

2023-01-11 15:32 UTC, hammady commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +          @logger.error error_message
This line can now move outside the `case` block.

2023-01-11 16:19 UTC, merged