Cast jvolume and jissue to integers
rayyansys/rayyan-scrapers pull request #46
Opened 2023-03-15 14:01 UTC by maboelnour

Closes #45

2023-03-15 15:08 UTC, hammady requested changes

2023-03-15 15:09 UTC, hammady commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +      mArticle.jvolume = item['volume'].to_i
It also fails tests. Please update tests where inputs are numeric strings, non-numeric strings, empty or nil.

2023-03-16 17:49 UTC, maboelnour commented on lib/rayyan-scrapers/mendeley_scraper.rb
> +      mArticle.jvolume = item['volume'].to_i
`nil.to_i` is `0` so it's safe.

Fun fact about ruby's nil: there is only one `nil` object: `nil.object_id` will always equal `8` on 64bits.

2023-03-16 18:41 UTC, hammady approved these changes

2023-03-16 18:41 UTC, merged